name: Deploy to Azure VM
on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Checkout code from the repository

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}

      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no dpacks-prod@${{ secrets.AZURE_VM_IP }} "
            sudo git clone https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_ACCESS_TOKEN }}@github.com/dpacks-technology/dpacks-storage-service.git ./storage
            cd storage
            sudo git fetch origin && sudo git pull origin main
            sudo docker stop dpacks-storage-service
            sudo docker rm dpacks-storage-service
            sudo docker build -t dpacks-storage-service:latest .
            sudo docker run -d --name dpacks-storage-service -p 4004:4004 dpacks-storage-service:latest"